[tox]
# Sphinx 9.1.0 requires Python >= 3.12
# Sphinx 9.0.0 requires Python >= 3.11
# last Sphinx 8.x.x release also requires Python >= 3.11
envlist = py311, py312 
skip_missing_interpreters = true

[testenv]
usedevelop = True
deps =
    pytest
    pytest-cov
    docutils
    requests
    jsonpointer
    pyyaml
commands =
    pip3 freeze
    pytest -rs --cov=sphinx-jsonschema --cov-report=term-missing --cov-report=html --cov-fail-under=25
